apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: wk-name-search
  labels:
    app: wk-name-search
spec:
  maxReplicaCount: 5
  minReplicaCount: 1
  pollingInterval: 15
  scaleTargetRef:
    name: wk-name-search
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://wk-name-search-prometheus-server:80
        metricName: cpu_usage
        query: sum(irate(process_cpu_seconds_total{app="wk-name-search"}[2m])) * 100
        threshold: '50'


